# Generated by Django 5.0.2 on 2026-02-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
    ]
