# Generated by Django 6.0.2 on 2026-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_reservation_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="confirmation_token",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Токен подтверждения",
            ),
        ),
    ]
