# Generated by Django 6.0.2 on 2026-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_reservation_confirmation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("staff", "Сотрудник"),
                    ("guest", "Гость"),
                ],
                default="guest",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
