# Generated by Django 6.0.2 on 2026-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_user_groups_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("chef", "Шеф-повар"),
                            ("sous_chef", "Су-шеф"),
                            ("manager", "Менеджер"),
                            ("waiter", "Официант"),
                            ("bartender", "Бармен"),
                            ("host", "Хостес"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "custom_position",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Другая должность",
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Фото (URL)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Биография"),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Instagram"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Telegram"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Член команды",
                "verbose_name_plural": "Члены команды",
                "db_table": "team_members",
                "ordering": ["order", "last_name", "first_name"],
            },
        ),
    ]
