# Generated by Django 6.0.2 on 2026-02-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=100, verbose_name="Имя гостя"),
                ),
                ("guest_email", models.CharField(max_length=200, verbose_name="Email")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ - Ужасно"),
                            (2, "⭐⭐ - Плохо"),
                            (3, "⭐⭐⭐ - Нормально"),
                            (4, "⭐⭐⭐⭐ - Хорошо"),
                            (5, "⭐⭐⭐⭐⭐ - Отлично"),
                        ],
                        default=5,
                        verbose_name="Рейтинг",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
